global:
  scrape_interval: 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          - 'grafana:3000'
          - 'go-app:2112'
          - 'python-app:8000'
          - 'redis_exporter:9121'
          - 'jmx_exporter:5556'

